### ISSUE TITLE
Ant - Unknown User Permission

### ISSUE THREAD

**Issue by dongidea** [afawcett/forcedotcom-enterprise-architecture#1]
Hi Andrew,

I got error "unknown user permission" when I try to migrate packaging org metadata to a new DE org. Error detail is as follow

![2014-12-31_12-02-59](https://cloud.githubusercontent.com/assets/7919226/5585648/55b359d2-90e5-11e4-9831-9606d877a546.png)

I'm in API ver 32.0, permission set member types in package.xml set as wildcard. The deployment success when I comment out permission set types. 

Could you give me any directions on this issue? It seems that the error is API version specific or dependency of ActivateOrder permission is missing.

Appreciate your help,
Thank you!
Dong.

**Comment by afawcett** [comment]
Yes, thank @aggressiveasparagus just seen this, thanks for helping out! :+1:

**Comment by imchikachirag** [comment]
> Best bet is either:
> 
> 1. go to Setup > Customize > Orders > Settings and **Enable Orders** or
> 2. open up `FormulaFOrce_Race_Analytics.permissionset` and delete those tags
> 
> (You'll also need to **Enable Chatter** from Setup > Customize > Chatter > Settings)

This worked, thanks!
