### ISSUE TITLE
Small issues with undeploy.xml

### ISSUE THREAD

**Issue by afaubel** [afawcett/forcedotcom-enterprise-architecture#2]
I found this resource whilst reading through my copy of the 'Force.com Enterprise Architecture' (So far, so excellent). Before than i had just live with the free 'extras' that SF provides with a new DEV org. Nice to have an easy way to get rid of these elements. Whilst using it though I hit three problems:

**1. Account.SLA__c**
In the Dev org I created there was a field on Account called 'SLA__c'. This was being used by a Case Assignment Rule called Standard and a Case Escalation Rule called Standard, so the SLA__c field could not be removed. Deleting these two rules resolved the issue

**2. Java 8 Version Issue**
Initially I tried to run it with Java 8. Unfortunately this failed with the following error:
ReferenceError: "importPackage" is not defined in <eval> at line number ...
It turns out that the issue is with Java 8 which no longer supports 'importPackage' since Rhino has been replaced by Nashorn. I've not tested it, but this suggests a workaround:
http://stackoverflow.com/questions/22502630/switching-from-rhino-to-nashorn
In my case I switched to Jave 7 and it worked OK.

**3. SF Domain**
On line 822 there is a reference to a Salesforce Domain. For my org I had to edit this to work with the org domain which in my case was different from emea.

I hope the above is useful.

Thanks for a great book.

Alan

**Comment by elukaweski** [comment]
Hi:

**Comment by afaubel** [comment]
Hi @elukaweski

**Comment by afawcett** [comment]
Thanks @afaubel for the feedback, glad your enjoying the book so far!

As referenced in the book the Ant tools have been taken from the FinancialForce repo [here](https://github.com/financialforcedev/df12-deployment-tools). It looks like the latest versions of these files have fixed your issues, so worth taking a look at those.

**Comment by afaubel** [comment]
Hi @afawcett 
Thanks for that. Yep, that solved all of the issues I found. Just goes to show I should read the whole book and not just dip into the bits I think I need to read :-)

**Comment by afawcett** [comment]
Ha no worries, enjoy the rest of your read, please feel free to drop a review on Amazon as well. :+1:
