### ISSUE TITLE
Question - build.xml in chapter 11

### ISSUE THREAD

**Issue by elukaweski** [afawcett/forcedotcom-enterprise-architecture#4]
Hi....the build.xml in sample code for chapter 11 and the master has a target named "package.installdemo".

What is this used for?
Thanks, Edwin

**Comment by afawcett** [comment]
Its a demo from an earlier chapter talking about automating things via metadata API and Ant. Helps if your wanting to automate installing dependent packages before deploying your code. Typically in a CI environment.

**Comment by elukaweski** [comment]
got it....interesting. Thanks for the reply

can you give me the specific reference in the book (e.g.page number) where it is used?

Thanks, Edwin

**Comment by afawcett** [comment]
I don't have the specific page number (as believe it or not i don't have my paper copy to hand), but looking through my drafts, i can see it was discussed in Chapter 1, under a sub-section entitled 'Automating package install'. Enjoy! :+1:

**Comment by elukaweski** [comment]
Page 27   :)
